<?php
    session_start();
    unset($_SESSION["session_username"]);
    unset($_SESSION["session_username"]);
    unset($_SESSION["email"]);
    unset($_SESSION["login"]);
    unset($_SESSION["password"]);
    session_destroy();
    header("location:index.php");
?>
