on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:

      - name: Extract branch name on push
        if: github.event_name != 'pull_request'
        shell: bash
        run: echo "::set-env name=BRANCH_NAME::$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: Extract branch name on pull request
        if: github.event_name == 'pull_request'
        run: echo "::set-env name=BRANCH_NAME::$(echo ${GITHUB_HEAD_REF})"

      - uses: actions/checkout@v1
      - name: 🚚 Get latest code
        uses: sebastianpopp/git-ftp-action@releases/v3
        with:
          url: ${{ secrets.FTP_SERVER }}/ascheulov
          user: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}

      - uses: actions/checkout@v1
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL }}
          SLACK_COLOR: ${{ secrets.SLACK_COLOR }}
          SLACK_MESSAGE: ${{ secrets.SLACK_MESSAGE }}
          SLACK_TITLE: ${{ secrets.SLACK_TITLE }}
          SLACK_FOOTER: ${{ secrets.SLACK_FOOTER }}
          SLACK_USERNAME: ${{ secrets.SLACK_USERNAME }}
          SLACK_ICON_EMOJI: ${{ secrets.SLACK_ICON_EMOJI }}
          MSG_MINIMAL: commit
