on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Set env.BRANCH
        run: echo "BRANCH=$(echo $GITHUB_REF | cut -d'/' -f 3)" >> $GITHUB_ENV

      - uses: actions/checkout@v1
      - name: 🚚 Get latest code
        uses: sebastianpopp/git-ftp-action@releases/v3
        with:
          url: ""
          user: ""
          password: ""

      - uses: actions/checkout@v1
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL }}
          SLACK_COLOR: ${{ secrets.SLACK_COLOR }}
          SLACK_MESSAGE: ${{ secrets.SLACK_MESSAGE }}
          SLACK_TITLE: ${{ secrets.SLACK_TITLE }}
          SLACK_FOOTER: ${{ secrets.SLACK_FOOTER }}
          SLACK_USERNAME: ${{ secrets.SLACK_USERNAME }}
          SLACK_ICON_EMOJI: ${{ secrets.SLACK_ICON_EMOJI }}
          MSG_MINIMAL: commit
